import {
  coreNode,
  coreNodes,
  descriptor,
  layout,
  scenarioEdge,
  scenarioNode,
} from "./helpers";
import type { ScenarioGraphDescriptorCatalogSubset } from "./model";

export const pipelineScenarioGraphDescriptors = {
  "streams-joins-windows": descriptor({
    scenarioId: "streams-joins-windows",
    replacesCoreProducerTopicEdge: true,
    nodes: [
      ...coreNodes({
        producer: layout(0),
        topic: layout(3),
        consumerGroup: layout(4),
      }),
      scenarioNode(
        "orders-stream",
        "Orders stream",
        "Left-side keyed records.",
        "simulated",
        "stream",
        layout(1, -1),
      ),
      scenarioNode(
        "payments-stream",
        "Payments stream",
        "Right-side keyed records.",
        "simulated",
        "stream",
        layout(1, 1),
      ),
      scenarioNode(
        "window-state-store",
        "Window state store",
        "Joins only equal keys inside the window and grace period.",
        "simulated",
        "stream",
        layout(2),
      ),
    ],
    edges: [
      scenarioEdge(
        "producer-orders",
        "producer",
        "orders-stream",
        "order",
        "simulated",
        "data",
      ),
      scenarioEdge(
        "producer-payments",
        "producer",
        "payments-stream",
        "payment",
        "simulated",
        "data",
      ),
      scenarioEdge(
        "orders-window",
        "orders-stream",
        "window-state-store",
        "same key candidate",
        "simulated",
        "data",
      ),
      scenarioEdge(
        "payments-window",
        "payments-stream",
        "window-state-store",
        "same key candidate",
        "simulated",
        "data",
      ),
      scenarioEdge(
        "window-topic",
        "window-state-store",
        "topic",
        "joined output only",
        "simulated",
        "data",
      ),
      scenarioEdge(
        "topic-group",
        "topic",
        "consumerGroup",
        "consume join result",
        "observed",
        "data",
      ),
    ],
  }),
  "outbox-cdc": descriptor({
    scenarioId: "outbox-cdc",
    replacesCoreProducerTopicEdge: true,
    nodes: [
      scenarioNode(
        "database-outbox",
        "Atomic database transaction",
        "Commits a business row and outbox row together.",
        "simulated",
        "database",
        layout(0),
      ),
      scenarioNode(
        "transaction-log",
        "Database WAL",
        "Orders committed outbox changes by LSN.",
        "simulated",
        "database",
        layout(1),
      ),
      scenarioNode(
        "cdc-connector",
        "CDC connector",
        "Publishes WAL changes and retries safely.",
        "simulated",
        "stream",
        layout(2),
      ),
      coreNode("topic", layout(3)),
      coreNode("consumerGroup", layout(4)),
    ],
    edges: [
      scenarioEdge(
        "outbox-wal",
        "database-outbox",
        "transaction-log",
        "atomic commit",
        "simulated",
        "data",
      ),
      scenarioEdge(
        "wal-cdc",
        "transaction-log",
        "cdc-connector",
        "ordered LSN",
        "simulated",
        "data",
      ),
      scenarioEdge(
        "cdc-topic",
        "cdc-connector",
        "topic",
        "publish and acknowledge",
        "simulated",
        "data",
      ),
      scenarioEdge(
        "topic-group",
        "topic",
        "consumerGroup",
        "idempotent consume",
        "observed",
        "data",
      ),
    ],
  }),
} satisfies ScenarioGraphDescriptorCatalogSubset<
  "streams-joins-windows" | "outbox-cdc"
>;
